name: nexum-api-dev

services:
  db:
    image: postgres:15-alpine
    container_name: nexum-postgres-dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - nexum-network-dev
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DATABASE_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: nexum-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - db
    restart: always
    networks:
      - nexum-network-dev

networks:
  nexum-network-dev:
    driver: bridge

volumes:
  pgdata-dev:
  node_modules:
