import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1775544656732 implements MigrationInterface {
    name = 'InitialSchema1775544656732'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."community_members_role_enum" AS ENUM('MEMBER', 'MODERATOR', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "community_members" ("id" SERIAL NOT NULL, "role" "public"."community_members_role_enum" NOT NULL DEFAULT 'MEMBER', "joinedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" integer, "communityId" integer, CONSTRAINT "PK_03dff82f9cfcb02498e9f5fc640" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."post_votes_type_enum" AS ENUM('UP', 'DOWN')`);
        await queryRunner.query(`CREATE TABLE "post_votes" ("id" SERIAL NOT NULL, "type" "public"."post_votes_type_enum" NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "postId" integer, "userId" integer, CONSTRAINT "UQ_aab7e33d6e62b0c1a848501991a" UNIQUE ("postId", "userId"), CONSTRAINT "PK_9582da033a0549ccd393cabe385" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."comment_votes_type_enum" AS ENUM('UP', 'DOWN')`);
        await queryRunner.query(`CREATE TABLE "comment_votes" ("id" SERIAL NOT NULL, "type" "public"."comment_votes_type_enum" NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "commentId" integer, "userId" integer, CONSTRAINT "UQ_dfdbe89dc8423c08d53bdc1ccfb" UNIQUE ("commentId", "userId"), CONSTRAINT "PK_2f0e8a57401e7d3fc0e966e771e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" SERIAL NOT NULL, "content" text NOT NULL, "upvotes" integer NOT NULL DEFAULT '0', "downvotes" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "authorId" integer, "postId" integer, "questionId" integer, "parentId" integer, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" SERIAL NOT NULL, "title" character varying(200) NOT NULL, "content" text NOT NULL, "searchContent" text NOT NULL, "searchVector" jsonb, "upvotes" integer NOT NULL DEFAULT '0', "downvotes" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "authorId" integer, "communityId" integer, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."communities_visibility_enum" AS ENUM('PUBLIC', 'PRIVATE')`);
        await queryRunner.query(`CREATE TABLE "communities" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "avatar" character varying(255), "coverImage" character varying(255), "visibility" "public"."communities_visibility_enum" NOT NULL DEFAULT 'PUBLIC', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" integer, CONSTRAINT "UQ_501bb6c8f7c8e8a7d614d9435f6" UNIQUE ("name"), CONSTRAINT "PK_fea1fe83c86ccde9d0a089e7ea2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."question_votes_type_enum" AS ENUM('UP', 'DOWN')`);
        await queryRunner.query(`CREATE TABLE "question_votes" ("id" SERIAL NOT NULL, "type" "public"."question_votes_type_enum" NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "questionId" integer, "userId" integer, CONSTRAINT "UQ_c320ad1cbdd87f967e76177a510" UNIQUE ("questionId", "userId"), CONSTRAINT "PK_4fcf37b1bcad3cc75921424dc07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."questions_urgency_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" SERIAL NOT NULL, "title" character varying(200) NOT NULL, "content" text NOT NULL, "searchContent" text NOT NULL, "searchVector" jsonb, "urgency" "public"."questions_urgency_enum" NOT NULL DEFAULT 'MEDIUM', "upvotes" integer NOT NULL DEFAULT '0', "downvotes" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "acceptedAnswerId" integer, "authorId" integer, "communityId" integer, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "answers" ("id" SERIAL NOT NULL, "content" text NOT NULL, "upvotes" integer NOT NULL DEFAULT '0', "downvotes" integer NOT NULL DEFAULT '0', "isAccepted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "authorId" integer, "questionId" integer, CONSTRAINT "PK_9c32cec6c71e06da0254f2226c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."answer_votes_type_enum" AS ENUM('UP', 'DOWN')`);
        await queryRunner.query(`CREATE TABLE "answer_votes" ("id" SERIAL NOT NULL, "type" "public"."answer_votes_type_enum" NOT NULL, "userId" integer, "answerId" integer, CONSTRAINT "UQ_7c0d88718e56e91ce473a76773e" UNIQUE ("userId", "answerId"), CONSTRAINT "PK_767f6bc508e4f2d6d08d65beb31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "follows" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "followerId" integer, "followingId" integer, CONSTRAINT "PK_8988f607744e16ff79da3b8a627" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('FOLLOW', 'POST_VOTE', 'QUESTION_VOTE', 'COMMENT_ON_POST', 'COMMENT_VOTE', 'ANSWER_ON_QUESTION', 'ANSWER_VOTE', 'ANSWER_ACCEPTED')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_entitytype_enum" AS ENUM('PROFILE', 'POST', 'QUESTION', 'COMMENT', 'ANSWER')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "entityType" "public"."notifications_entitytype_enum" NOT NULL, "entityId" integer NOT NULL, "message" text NOT NULL, "targetUrl" character varying(255) NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "recipientId" integer, "actorId" integer, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "username" character varying(50) NOT NULL, "fullName" character varying(100), "bio" character varying(255), "coverPhoto" character varying(255), "avatar" character varying(255), "email" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "refreshToken" character varying(255), "followersCount" integer NOT NULL DEFAULT '0', "followingCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."community_invites_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'DECLINED')`);
        await queryRunner.query(`CREATE TABLE "community_invites" ("id" SERIAL NOT NULL, "status" "public"."community_invites_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "communityId" integer, "invitedUserId" integer, "invitedById" integer, CONSTRAINT "UQ_4ef0b97271c4d44c539128662f0" UNIQUE ("communityId", "invitedUserId"), CONSTRAINT "PK_0233b97158e7d5224acf1ab7871" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts_tags_tags" ("postsId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_0102fd077ecbe473388af8f3358" PRIMARY KEY ("postsId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf364c7e6905b285c4b55a0034" ON "posts_tags_tags" ("postsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce163a967812183a51b044f740" ON "posts_tags_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "communities_tags_tags" ("communitiesId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_e441154a957b734f3d76d7e346e" PRIMARY KEY ("communitiesId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c9df47bc97aa57f24d50d6544" ON "communities_tags_tags" ("communitiesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06bcd8c73049418680cd394947" ON "communities_tags_tags" ("tagsId") `);
        await queryRunner.query(`CREATE TABLE "questions_tags_tags" ("questionsId" integer NOT NULL, "tagsId" integer NOT NULL, CONSTRAINT "PK_6c1ea3a815ea62263aaf7cfcd80" PRIMARY KEY ("questionsId", "tagsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91353dfa02de18aeab04ef3a60" ON "questions_tags_tags" ("questionsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ebfd7ef95ffa54c9997580c8d2" ON "questions_tags_tags" ("tagsId") `);
        await queryRunner.query(`ALTER TABLE "community_members" ADD CONSTRAINT "FK_dff8a6a8aabc10e2c61e57a45f2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community_members" ADD CONSTRAINT "FK_692f4422c79d6efe4f2cfbe6063" FOREIGN KEY ("communityId") REFERENCES "communities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_votes" ADD CONSTRAINT "FK_74c47fd124434b6ae3684a074f2" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_votes" ADD CONSTRAINT "FK_d6e4623a4f86aaaa06605a003cd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_votes" ADD CONSTRAINT "FK_db0f40562fcbaec17222882574b" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_votes" ADD CONSTRAINT "FK_c70cad98b28ff8502621ad0e6f3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4548cc4a409b8651ec75f70e280" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8db2a234357898ee18a16f5d409" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81" FOREIGN KEY ("parentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_e5f99a0b3edb7e1867f44b2cf4c" FOREIGN KEY ("communityId") REFERENCES "communities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communities" ADD CONSTRAINT "FK_2d9086cef1ffd5148f90a9fab5d" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_votes" ADD CONSTRAINT "FK_fb7b67f20b9ef18a2bc082fc74e" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_votes" ADD CONSTRAINT "FK_a5456f539a954a91c7b808347d5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_ca251175a93ed97051be0df6e6f" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_b6417cc14e98475aad3a7333a17" FOREIGN KEY ("communityId") REFERENCES "communities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_eb21b7568b66f2fbc1d0f8c0ddd" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_c38697a57844f52584abdb878d7" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_votes" ADD CONSTRAINT "FK_3a9e5a77d85cc2daed4656a6ded" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answer_votes" ADD CONSTRAINT "FK_d000391d3f93664a25350b85d42" FOREIGN KEY ("answerId") REFERENCES "answers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb" FOREIGN KEY ("followingId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_db873ba9a123711a4bff527ccd5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_44412a2d6f162ff4dc1697d0db7" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community_invites" ADD CONSTRAINT "FK_0f0385820ee93296192f2cca24e" FOREIGN KEY ("communityId") REFERENCES "communities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community_invites" ADD CONSTRAINT "FK_8bcd0aeaa5b12793d0b8b76b477" FOREIGN KEY ("invitedUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community_invites" ADD CONSTRAINT "FK_c2c65ec718f173c46d3d91da14e" FOREIGN KEY ("invitedById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts_tags_tags" ADD CONSTRAINT "FK_cf364c7e6905b285c4b55a00343" FOREIGN KEY ("postsId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "posts_tags_tags" ADD CONSTRAINT "FK_ce163a967812183a51b044f7404" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communities_tags_tags" ADD CONSTRAINT "FK_0c9df47bc97aa57f24d50d65440" FOREIGN KEY ("communitiesId") REFERENCES "communities"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "communities_tags_tags" ADD CONSTRAINT "FK_06bcd8c73049418680cd394947a" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions_tags_tags" ADD CONSTRAINT "FK_91353dfa02de18aeab04ef3a60e" FOREIGN KEY ("questionsId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "questions_tags_tags" ADD CONSTRAINT "FK_ebfd7ef95ffa54c9997580c8d27" FOREIGN KEY ("tagsId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "questions_tags_tags" DROP CONSTRAINT "FK_ebfd7ef95ffa54c9997580c8d27"`);
        await queryRunner.query(`ALTER TABLE "questions_tags_tags" DROP CONSTRAINT "FK_91353dfa02de18aeab04ef3a60e"`);
        await queryRunner.query(`ALTER TABLE "communities_tags_tags" DROP CONSTRAINT "FK_06bcd8c73049418680cd394947a"`);
        await queryRunner.query(`ALTER TABLE "communities_tags_tags" DROP CONSTRAINT "FK_0c9df47bc97aa57f24d50d65440"`);
        await queryRunner.query(`ALTER TABLE "posts_tags_tags" DROP CONSTRAINT "FK_ce163a967812183a51b044f7404"`);
        await queryRunner.query(`ALTER TABLE "posts_tags_tags" DROP CONSTRAINT "FK_cf364c7e6905b285c4b55a00343"`);
        await queryRunner.query(`ALTER TABLE "community_invites" DROP CONSTRAINT "FK_c2c65ec718f173c46d3d91da14e"`);
        await queryRunner.query(`ALTER TABLE "community_invites" DROP CONSTRAINT "FK_8bcd0aeaa5b12793d0b8b76b477"`);
        await queryRunner.query(`ALTER TABLE "community_invites" DROP CONSTRAINT "FK_0f0385820ee93296192f2cca24e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_44412a2d6f162ff4dc1697d0db7"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_db873ba9a123711a4bff527ccd5"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_fdb91868b03a2040db408a53331"`);
        await queryRunner.query(`ALTER TABLE "answer_votes" DROP CONSTRAINT "FK_d000391d3f93664a25350b85d42"`);
        await queryRunner.query(`ALTER TABLE "answer_votes" DROP CONSTRAINT "FK_3a9e5a77d85cc2daed4656a6ded"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_c38697a57844f52584abdb878d7"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_eb21b7568b66f2fbc1d0f8c0ddd"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_b6417cc14e98475aad3a7333a17"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_ca251175a93ed97051be0df6e6f"`);
        await queryRunner.query(`ALTER TABLE "question_votes" DROP CONSTRAINT "FK_a5456f539a954a91c7b808347d5"`);
        await queryRunner.query(`ALTER TABLE "question_votes" DROP CONSTRAINT "FK_fb7b67f20b9ef18a2bc082fc74e"`);
        await queryRunner.query(`ALTER TABLE "communities" DROP CONSTRAINT "FK_2d9086cef1ffd5148f90a9fab5d"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_e5f99a0b3edb7e1867f44b2cf4c"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8db2a234357898ee18a16f5d409"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4548cc4a409b8651ec75f70e280"`);
        await queryRunner.query(`ALTER TABLE "comment_votes" DROP CONSTRAINT "FK_c70cad98b28ff8502621ad0e6f3"`);
        await queryRunner.query(`ALTER TABLE "comment_votes" DROP CONSTRAINT "FK_db0f40562fcbaec17222882574b"`);
        await queryRunner.query(`ALTER TABLE "post_votes" DROP CONSTRAINT "FK_d6e4623a4f86aaaa06605a003cd"`);
        await queryRunner.query(`ALTER TABLE "post_votes" DROP CONSTRAINT "FK_74c47fd124434b6ae3684a074f2"`);
        await queryRunner.query(`ALTER TABLE "community_members" DROP CONSTRAINT "FK_692f4422c79d6efe4f2cfbe6063"`);
        await queryRunner.query(`ALTER TABLE "community_members" DROP CONSTRAINT "FK_dff8a6a8aabc10e2c61e57a45f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebfd7ef95ffa54c9997580c8d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91353dfa02de18aeab04ef3a60"`);
        await queryRunner.query(`DROP TABLE "questions_tags_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06bcd8c73049418680cd394947"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c9df47bc97aa57f24d50d6544"`);
        await queryRunner.query(`DROP TABLE "communities_tags_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce163a967812183a51b044f740"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf364c7e6905b285c4b55a0034"`);
        await queryRunner.query(`DROP TABLE "posts_tags_tags"`);
        await queryRunner.query(`DROP TABLE "community_invites"`);
        await queryRunner.query(`DROP TYPE "public"."community_invites_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_entitytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "follows"`);
        await queryRunner.query(`DROP TABLE "answer_votes"`);
        await queryRunner.query(`DROP TYPE "public"."answer_votes_type_enum"`);
        await queryRunner.query(`DROP TABLE "answers"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TYPE "public"."questions_urgency_enum"`);
        await queryRunner.query(`DROP TABLE "question_votes"`);
        await queryRunner.query(`DROP TYPE "public"."question_votes_type_enum"`);
        await queryRunner.query(`DROP TABLE "communities"`);
        await queryRunner.query(`DROP TYPE "public"."communities_visibility_enum"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "comment_votes"`);
        await queryRunner.query(`DROP TYPE "public"."comment_votes_type_enum"`);
        await queryRunner.query(`DROP TABLE "post_votes"`);
        await queryRunner.query(`DROP TYPE "public"."post_votes_type_enum"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "community_members"`);
        await queryRunner.query(`DROP TYPE "public"."community_members_role_enum"`);
    }

}
